# Camera Parameters
camera:
  fps: 240
  pixel_size: 0.0000048
  width: 1024
  height: 1280
  focal_length: 0.008

# Ball Parameters
ball:
  radius: 0.0373

# Setup Parameters
setup:
  camera_upward_tilt_angle: 10.0
  initial_distance_between_camera_and_ball: 4.0

# Strategy Parameters
strategy:
  ball_detector: "default"
  ball_detector: "default"
  world_coordinate_estimator: "default"
  speed_vector_estimator: "default"

# Ball Detector Parameters
ball_detector:
  yolov8_model_size: "x" # n s m l x
  ball_class_id: 32
  initial_search_region_bbox: [263, 390, 500, 500] # Center of the image with 500x500 box
  history_depth: 5
  bbox_size_multiplier: 10.0

# World Coordinate Estimator Parameters
world_coordinate_estimator:
  dummy_parameter: 0

# Speed Vector Estimator Parameters
speed_vector_estimator:
  history_depth: 15

# Experiment Parameters
experiment:
  output_file_path: "output.csv"